#!/usr/bin/env python3
"""Regenerate the skill index in README.md from the tree itself.

The README used to carry hand-counted skill totals. Three of them were wrong by
the time anyone checked: engineering claimed 81 against 108 on disk,
engineering-team claimed 52 against 51, productivity claimed 10 against 20.
Counting is the machine's job. Prose about each domain stays human-written in
docs/domain-descriptions.json.

    scripts/generate_index.py --write     # update README.md in place
    scripts/generate_index.py --check     # fail if README.md is stale

Exit codes
    0  README.md matches the tree
    1  README.md is stale (--check)
    2  usage or environment error
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SKILLS_ROOT = REPO_ROOT / "skills"
README = REPO_ROOT / "README.md"
DESCRIPTIONS = REPO_ROOT / "docs" / "domain-descriptions.json"
MANIFEST = SKILLS_ROOT / "vendor.manifest.json"

BEGIN = "<!-- BEGIN GENERATED: skill-index (scripts/generate_index.py) -->"
END = "<!-- END GENERATED: skill-index -->"


def count_skills(root: Path) -> int:
    total = 0
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d != ".git"]
        if "SKILL.md" in filenames:
            total += 1
    return total


def vendored_dests() -> dict:
    if not MANIFEST.exists():
        return {}
    data = json.loads(MANIFEST.read_text(encoding="utf-8"))
    return {s["dest"].strip("/"): s for s in data.get("sources", [])}


def render() -> str:
    descriptions = (
        json.loads(DESCRIPTIONS.read_text(encoding="utf-8")) if DESCRIPTIONS.exists() else {}
    )
    vendored = vendored_dests()

    local_rows, vendor_rows = [], []
    for entry in sorted(SKILLS_ROOT.iterdir(), key=lambda p: p.name):
        if not entry.is_dir() or entry.name.startswith("."):
            continue
        rel = f"skills/{entry.name}"
        count = count_skills(entry)
        desc = descriptions.get(entry.name, "")
        if rel in vendored:
            src = vendored[rel]
            repo = src["repo"].rstrip("/")
            sha = src.get("pinned_commit", "")
            vendor_rows.append(
                f"| [`{entry.name}`](./{rel}/) | {count} | [{src['name']}]({repo}) | "
                f"{src.get('license','see upstream')} | [`{sha[:12]}`]({repo}/commit/{sha}) | "
                f"[attribution](./{rel}/ATTRIBUTION.md) |"
            )
        else:
            local_rows.append(f"| [`{entry.name}`](./{rel}/) | {count} | {desc} |")

    total = count_skills(SKILLS_ROOT)
    lines = [
        BEGIN,
        "",
        f"**{total} skills** across {len(local_rows) + len(vendor_rows)} directories. "
        "Counts and licence pins on this page are generated by "
        "[`scripts/generate_index.py`](./scripts/generate_index.py) and verified in CI, so they "
        "cannot drift from the tree.",
        "",
        "### Skill domains",
        "",
        "| Domain | Skills | Description |",
        "| --- | ---: | --- |",
        *local_rows,
        "",
        "### Vendored collections",
        "",
        "Imported verbatim from an upstream project, refreshed automatically every two weeks by "
        "[`.github/workflows/sync-vendored-skills.yml`](./.github/workflows/sync-vendored-skills.yml). "
        "Every skill directory carries a `PROVENANCE.md` naming its upstream path and commit. "
        "Full licence record: [`THIRD_PARTY_NOTICES.md`](./THIRD_PARTY_NOTICES.md).",
        "",
        "| Collection | Skills | Upstream | Licence | Pinned commit | Attribution |",
        "| --- | ---: | --- | --- | --- | --- |",
        *vendor_rows,
        "",
        END,
    ]
    return "\n".join(lines)


def splice(text: str, block: str) -> str:
    if BEGIN in text and END in text:
        head = text.split(BEGIN)[0]
        tail = text.split(END, 1)[1]
        return head + block + tail
    return text.rstrip() + "\n\n" + block + "\n"


def main(argv: list) -> int:
    ap = argparse.ArgumentParser(description="Regenerate the README skill index.")
    mode = ap.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = ap.parse_args(argv)

    if not README.exists():
        print(f"error: no README.md at {README}", file=sys.stderr)
        return 2

    current = README.read_text(encoding="utf-8")
    updated = splice(current, render())

    if args.check:
        if current != updated:
            print(
                "error: README.md skill index is stale. Run scripts/generate_index.py --write",
                file=sys.stderr,
            )
            return 1
        print("README.md skill index is up to date")
        return 0

    if current == updated:
        print("README.md already up to date")
        return 0
    README.write_text(updated, encoding="utf-8")
    print("README.md skill index regenerated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
