#!/usr/bin/env python3
"""Import and refresh vendored upstream content.

One code path serves both jobs. The first import of an upstream project and the
scheduled refresh two weeks later run exactly the same function, so a vendored
directory cannot drift into a hand-maintained fork by accident.

Reads skills/vendor.manifest.json. Standard library only.

    scripts/sync_vendor.py --validate-manifest  # offline consistency check, used by CI
    scripts/sync_vendor.py --check              # report drift vs upstream, write nothing
    scripts/sync_vendor.py --sync               # apply upstream into the tree
    scripts/sync_vendor.py --sync --source pstack
    scripts/sync_vendor.py --check --output json

--validate-manifest needs no network, so it can gate every pull request. --check
and --sync clone upstream and belong in the scheduled refresh, where an upstream
commit moving is news rather than a broken build.

## Why a source declares `paths` rather than one subdirectory

The first vendored project kept everything under `skills/`. The second,
job-hunt-skills, has 47 links from its skills into a sibling `guides/` directory
and more into `templates/`. Copying only `skills/` produces a tree whose internal
links all point at nothing.

So a source maps a list of upstream subtrees into its own vendored root, and the
mapping preserves the relative distance between them. Two kinds:

    skill-collection  a directory of skill directories. Each selected child is
                      tracked individually, gets a PROVENANCE.md, and appears in
                      the added/removed/changed report.
    support           a subtree the skills link into. Copied whole, or filtered by
                      `include` file globs, with one PROVENANCE.md at its root.

## Why ownership is recorded rather than inferred

An earlier version decided which directories it owned by listing the children of
a destination. That is wrong in two ways an adversarial review demonstrated. A
`skills -> ""` collection deleted a sibling `guides/` support tree it did not own,
and removing a `paths` entry from the manifest orphaned the tree it used to
manage, leaving redistributed content published with nothing tracking it.

Each destination now carries `.vendor-owned.json`, written by this script, listing
exactly what the previous run put there. A sync deletes what it used to own and no
longer does, and touches nothing else.

## Symlinks are rejected, not followed

`shutil.copytree` dereferences symlinks by default. A moving upstream could add
`secret -> /home/runner/work/_temp/.../file` and the scheduled job would commit
the contents of a runner-local path into a public pull request. Every symlink in
an upstream tree is a hard error here.

Exit codes
    0  no drift (--check), sync applied cleanly (--sync), or manifest consistent
    1  drift detected, inconsistent manifest, or a mandatory skill is missing
    2  usage, environment, or safety error
"""

from __future__ import annotations

import argparse
import datetime as _dt
import fnmatch
import hashlib
import json
import os
import posixpath
import re
import shutil
import stat
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
MANIFEST_PATH = REPO_ROOT / "skills" / "vendor.manifest.json"
NOTICES_PATH = REPO_ROOT / "THIRD_PARTY_NOTICES.md"
INVENTORY_PATH = REPO_ROOT / "docs" / "third-party-inventory.json"
OWNERSHIP_FILE = ".vendor-owned.json"
GENERATED_BANNER = "<!-- generated by scripts/sync_vendor.py -- do not edit by hand -->"
SHA_RE = re.compile(r"^[0-9a-f]{40}$")
SKILL_COLLECTION = "skill-collection"
SUPPORT = "support"
GENERATED_NAMES = {"PROVENANCE.md", OWNERSHIP_FILE}


# --------------------------------------------------------------------------- io


def _fail(msg: str, code: int = 2):
    print(f"error: {msg}", file=sys.stderr)
    raise SystemExit(code)


def _run(args: list, cwd: "Path | None" = None) -> str:
    proc = subprocess.run(args, cwd=str(cwd) if cwd else None, capture_output=True, text=True)
    if proc.returncode != 0:
        _fail(f"command failed: {' '.join(args)}\n{proc.stderr.strip()}")
    return proc.stdout.strip()


def load_manifest() -> dict:
    if not MANIFEST_PATH.exists():
        _fail(f"missing manifest: {MANIFEST_PATH}")
    try:
        return json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        _fail(f"manifest is not valid JSON: {exc}")


def _write(path: Path, text: str) -> bool:
    """Write only when content changes. Returns True when the file changed."""
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == text:
        return False
    path.write_text(text, encoding="utf-8")
    return True


def _rel(from_dir: Path, to_path: Path) -> str:
    """Markdown-safe relative link between two paths inside the repository."""
    return os.path.relpath(to_path, from_dir).replace(os.sep, "/")


# ------------------------------------------------------------------- path safety


def safe_segment(value: str, label: str, source_id: str) -> str:
    """A manifest-supplied path fragment, validated before it touches the disk.

    A manifest is data, and this script writes and deletes based on it, so the
    data is treated as untrusted. `dest: ../../etc` used to escape the repository
    root entirely.
    """
    raw = (value or "").strip()
    if not raw:
        return ""
    # Absoluteness is checked before any stripping. Testing it afterwards was a
    # bug in the first version of this guard: `/etc` became `etc` and passed.
    if (
        raw.startswith("/")
        or raw.startswith("\\")
        or Path(raw).is_absolute()
        or re.match(r"^[A-Za-z]:", raw)
    ):
        _fail(f"[{source_id}] `{label}` must be a repository-relative path, got `{value}`")
    cleaned = raw.strip("/")
    if not cleaned:
        return ""
    parts = [p for p in cleaned.replace("\\", "/").split("/")]
    for part in parts:
        if part in ("", ".", ".."):
            _fail(
                f"[{source_id}] `{label}` may not contain empty, `.` or `..` segments, got `{value}`"
            )
    return "/".join(parts)


def resolve_under(root: Path, relative: str, label: str, source_id: str) -> Path:
    """Join and prove the result stays inside `root`."""
    target = (root / relative).resolve() if relative else root.resolve()
    root_resolved = root.resolve()
    if target != root_resolved and root_resolved not in target.parents:
        _fail(f"[{source_id}] `{label}` resolves outside {root_resolved}: {target}")
    return target


def assert_no_symlinks(root: Path, source_id: str, upstream_label: str) -> None:
    """Refuse an upstream tree containing any symlink.

    Following one lets a moving upstream read an arbitrary runner path and have
    its contents committed to a public pull request.
    """
    if root.is_symlink():
        _fail(f"[{source_id}] upstream `{upstream_label}` is a symlink; refusing to vendor it")
    for dirpath, dirnames, filenames in os.walk(root, followlinks=False):
        for name in list(dirnames) + list(filenames):
            candidate = Path(dirpath) / name
            if candidate.is_symlink():
                shown = candidate.relative_to(root).as_posix()
                _fail(
                    f"[{source_id}] upstream `{upstream_label}` contains a symlink at `{shown}` "
                    f"-> `{os.readlink(candidate)}`. Symlinks are never vendored: following one "
                    f"would let upstream publish the contents of an arbitrary runner path. "
                    f"Exclude the path in the manifest or raise it with upstream."
                )


# ---------------------------------------------------------------- fingerprints


def tree_digest(root: Path) -> str:
    """Order-stable digest of a directory tree.

    Hashes entry type, relative path, executable bit and content, and records
    empty directories. An earlier version hashed only file path and content, so a
    chmod, an added empty directory, or a symlink replacing a file with identical
    bytes were all invisible to drift detection.

    Files this repository generates are excluded. Including them would make every
    vendored tree look permanently different from its upstream.
    """
    if not root.exists():
        return ""
    entries = []
    for dirpath, dirnames, filenames in os.walk(root, followlinks=False):
        dirnames[:] = sorted(d for d in dirnames if d != ".git")
        here = Path(dirpath)
        if not dirnames and not filenames:
            entries.append(("d", here.relative_to(root).as_posix(), "", ""))
        for name in sorted(filenames):
            if name in GENERATED_NAMES:
                continue
            full = here / name
            rel = full.relative_to(root).as_posix()
            if full.is_symlink():
                entries.append(("l", rel, "", os.readlink(full)))
                continue
            mode = "x" if os.stat(full).st_mode & stat.S_IXUSR else "-"
            entries.append(("f", rel, mode, hashlib.sha256(full.read_bytes()).hexdigest()))
    digest = hashlib.sha256()
    for kind, rel, mode, payload in sorted(entries):
        digest.update(f"{kind}\0{rel}\0{mode}\0{payload}\n".encode("utf-8"))
    return digest.hexdigest()


def _selected(names: list, include, exclude: list) -> list:
    """Apply include and exclude globs.

    `include` absent means everything. `include: []` means nothing, which is what
    a maintainer disabling a mapping writes. Conflating the two was a fail-open.
    """
    patterns = ["*"] if include is None else list(include)
    keep = []
    for name in sorted(names):
        if not any(fnmatch.fnmatch(name, pat) for pat in patterns):
            continue
        if any(fnmatch.fnmatch(name, pat) for pat in exclude or []):
            continue
        keep.append(name)
    return keep


def _child_dirs(root: Path) -> list:
    if not root.is_dir():
        return []
    return sorted(d.name for d in root.iterdir() if d.is_dir() and not d.name.startswith("."))


def _has_skill(path: Path) -> bool:
    return (path / "SKILL.md").is_file()


def _copy_tree(src: Path, dst: Path, file_include=None) -> None:
    """Copy without following symlinks. Optionally filter files by glob."""
    for dirpath, dirnames, filenames in os.walk(src, followlinks=False):
        dirnames[:] = sorted(d for d in dirnames if d != ".git")
        rel = Path(dirpath).relative_to(src)
        for name in sorted(filenames):
            if file_include is not None and not any(
                fnmatch.fnmatch(name, pat) or fnmatch.fnmatch((rel / name).as_posix(), pat)
                for pat in file_include
            ):
                continue
            target = dst / rel / name
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(Path(dirpath) / name, target, follow_symlinks=False)
        if file_include is None:
            (dst / rel).mkdir(parents=True, exist_ok=True)


# ------------------------------------------------------------------- ownership


def read_ownership(dest_root: Path) -> list:
    path = dest_root / OWNERSHIP_FILE
    if not path.exists():
        return []
    try:
        return sorted(set(json.loads(path.read_text(encoding="utf-8")).get("paths", [])))
    except (json.JSONDecodeError, AttributeError):
        return []


def write_ownership(dest_root: Path, owned: list, source_id: str) -> None:
    _write(
        dest_root / OWNERSHIP_FILE,
        json.dumps(
            {
                "$comment": (
                    "Written by scripts/sync_vendor.py. Lists exactly what the last sync placed "
                    "in this directory, so the next sync can delete what it no longer owns "
                    "without inferring ownership from whatever happens to be here. Do not edit."
                ),
                "source": source_id,
                "paths": sorted(set(owned)),
            },
            indent=2,
        )
        + "\n",
    )


# ------------------------------------------------------------------- upstream


def fetch_upstream(source: dict, workdir: Path) -> "tuple[Path, str]":
    ref = source.get("ref") or "HEAD"
    dest = workdir / source["id"]
    _run(["git", "clone", "--quiet", "--depth", "1", "--branch", ref, source["repo"], str(dest)])
    return dest, _run(["git", "rev-parse", "HEAD"], cwd=dest)


# ------------------------------------------------------------------ rendering


def _licence_summary(source: dict) -> str:
    primary = source.get("license", "see upstream")
    extra = [entry["license"] for entry in source.get("additional_licenses") or []]
    return primary if not extra else f"{primary}, plus {', '.join(sorted(set(extra)))}"


def provenance_text(source: dict, upstream_path: str, local_dir: Path, sha: str, kind: str) -> str:
    repo = source["repo"].rstrip("/")
    dest_root = REPO_ROOT / source["dest"]
    lic_link = _rel(local_dir, dest_root / "LICENSE.upstream")
    att_link = _rel(local_dir, dest_root / "ATTRIBUTION.md")
    wf_link = _rel(local_dir, REPO_ROOT / ".github/workflows/sync-vendored-skills.yml")

    rows = [
        f"| Upstream project | [{source['name']}]({repo}) |",
        f"| Upstream path | `{upstream_path}` |",
        f"| Pinned commit | [`{sha[:12]}`]({repo}/commit/{sha}) |",
        f"| Permalink | {repo}/tree/{sha}/{upstream_path} |",
        f"| Original author | {source.get('author', 'see upstream')} |",
        f"| Upstream licence | {_licence_summary(source)} |",
        f"| Licence copy | [`{lic_link}`]({lic_link}) |",
        f"| Full attribution | [`{att_link}`]({att_link}) |",
        f"| Content kind | {kind} |",
        f"| Refresh cadence | At least every two weeks by [`{wf_link}`]({wf_link}) |",
    ]
    if source.get("upstream_of_upstream"):
        rows.append(f"| Upstream's own source | {source['upstream_of_upstream']} |")

    manifest_link = _rel(local_dir, MANIFEST_PATH)
    return "\n".join(
        [
            GENERATED_BANNER,
            "",
            f"# Provenance: `{local_dir.name}`",
            "",
            "This directory is vendored, unmodified, from an upstream project. Do not edit it here.",
            "",
            "| Field | Value |",
            "| --- | --- |",
            *rows,
            "",
            "## Changing this",
            "",
            "Send the change to the upstream project. If this repository must diverge, remove the",
            f"entry from [`{manifest_link}`]({manifest_link}), copy it to a non-vendored path, and",
            "record why in the collection's `ATTRIBUTION.md`. Local edits made in place are silently",
            "reverted by the next scheduled sync.",
            "",
        ]
    )


def attribution_text(source: dict, sha: str, plan: list) -> str:
    repo = source["repo"].rstrip("/")
    dest_root = REPO_ROOT / source["dest"]
    script_link = _rel(dest_root, REPO_ROOT / "scripts/sync_vendor.py")
    wf_link = _rel(dest_root, REPO_ROOT / ".github/workflows/sync-vendored-skills.yml")
    manifest_link = _rel(dest_root, MANIFEST_PATH)

    out = [
        GENERATED_BANNER,
        "",
        f"# Attribution: {source['name']}",
        "",
        f"Everything in this directory was copied from [{source['name']}]({repo}) at commit",
        f"[`{sha}`]({repo}/commit/{sha}), pinned on {source.get('pinned_at', 'n/a')}.",
        "",
        f"- **Upstream project:** <{repo}>",
        f"- **Original author:** {source.get('author', 'see upstream')}",
        f"- **Primary licence:** {source.get('license', 'see upstream')}, reproduced verbatim in "
        "[`LICENSE.upstream`](./LICENSE.upstream)",
        f"- **Tracked by:** [`{manifest_link}`]({manifest_link})",
        f"- **Refreshed by:** [`{script_link}`]({script_link}), run at least every two weeks by "
        f"[`{wf_link}`]({wf_link})",
    ]
    if source.get("upstream_of_upstream"):
        out.append(f"- **Upstream's own source:** {source['upstream_of_upstream']}")
    out += [
        "",
        "No functional changes were made to the vendored content. This repository adds only a",
        "`PROVENANCE.md` per vendored directory, a `.vendor-owned.json` ownership record, and this",
        "file.",
    ]

    extra = source.get("additional_licenses") or []
    if extra:
        out += [
            "",
            "## Additional licences inside this import",
            "",
            "The primary licence above does not cover every file here. These do.",
            "",
            "| Files | Licence | Copyright | Licence text |",
            "| --- | --- | --- | --- |",
        ]
        for entry in extra:
            out.append(
                f"| `{entry['path']}` | {entry['license']} | {entry.get('copyright','see licence text')} "
                f"| [`{entry['license_file']}`](./{entry['license_file']}) |"
            )

    out += [
        "",
        "## Layout",
        "",
        "Upstream subtrees are mapped so that the relative links inside them keep resolving.",
        "",
        "| Upstream path | Vendored to | Kind |",
        "| --- | --- | --- |",
    ]
    for spec in plan:
        shown = spec["to"] or "."
        out.append(f"| `{spec['from'] or '.'}` | [`{shown}/`](./{spec['to']}) | {spec['kind']} |")

    for spec in plan:
        if spec["kind"] != SKILL_COLLECTION:
            continue
        skills = [n for n in spec["selected"] if n in spec.get("with_skill", [])]
        others = [n for n in spec["selected"] if n not in skills]
        out += [
            "",
            f"## Imported skills from `{spec['from']}` ({len(skills)})",
            "",
            "| Skill | Upstream permalink |",
            "| --- | --- |",
        ]
        for name in skills:
            upstream_path = posixpath.join(spec["from"], name) if spec["from"] else name
            local = posixpath.join(spec["to"], name) if spec["to"] else name
            out.append(
                f"| [`{name}`](./{local}/) | [`{upstream_path}`]({repo}/tree/{sha}/{upstream_path}) |"
            )
        if others:
            out += [
                "",
                f"Also imported from `{spec['from']}`, carrying no `SKILL.md` and therefore not "
                "skills: " + ", ".join(f"`{n}`" for n in others) + ".",
            ]

    mandatory = source.get("mandatory") or []
    if mandatory:
        out += ["", "## Mandatory imports", "", source.get("mandatory_reason", ""), ""]
        for name in mandatory:
            out.append(f"- `{name}`")

    reasons = {}
    for spec in plan:
        reasons.update(spec.get("exclude_reasons") or {})
    if reasons:
        out += [
            "",
            "## Deliberate exclusions",
            "",
            "Upstream content left out of this repository, and why. Recorded so the decision is",
            "auditable rather than looking like an incomplete import.",
            "",
            "| Upstream path | Reason |",
            "| --- | --- |",
        ]
        for name in sorted(reasons):
            out.append(f"| `{name}` | {reasons[name]} |")

    if source.get("limitations"):
        out += ["", "## Known limitations of this import", ""]
        for item in source["limitations"]:
            out.append(f"- {item}")

    if source.get("notes"):
        out += ["", "## Notes", "", source["notes"]]
    out.append("")
    return "\n".join(out)


def load_inventory() -> dict:
    if not INVENTORY_PATH.exists():
        _fail(f"missing third-party inventory: {INVENTORY_PATH}")
    return json.loads(INVENTORY_PATH.read_text(encoding="utf-8"))


def notices_text(manifest: dict) -> str:
    inventory = load_inventory()
    out = [
        GENERATED_BANNER,
        "",
        "# Third-party notices",
        "",
        "This repository redistributes work from the projects below. Each entry keeps its original",
        "licence, its original copyright, and a link back to the source. Nothing here changes the",
        "licence of the original work.",
        "",
        "Two tiers, because they carry different guarantees.",
        "",
        "## Tier 1: under automated refresh",
        "",
        "Declared in [`skills/vendor.manifest.json`](./skills/vendor.manifest.json), imported by",
        "[`scripts/sync_vendor.py`](./scripts/sync_vendor.py), pinned to a full commit, and",
        "refreshed at least every two weeks. Provenance presence is enforced on every pull request.",
        "",
        "| Upstream project | Author | Licence | Vendored to | Pinned commit | Attribution |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for src in manifest.get("sources", []):
        repo = src["repo"].rstrip("/")
        sha = src.get("pinned_commit", "")
        short = f"[`{sha[:12]}`]({repo}/commit/{sha})" if sha else "unpinned"
        out.append(
            f"| [{src['name']}]({repo}) | {src.get('author','see upstream')} | "
            f"{_licence_summary(src)} | `{src['dest']}/` | {short} | "
            f"[ATTRIBUTION.md](./{src['dest']}/ATTRIBUTION.md) |"
        )

    extras = [
        (src, entry)
        for src in manifest.get("sources", [])
        for entry in src.get("additional_licenses") or []
    ]
    if extras:
        out += [
            "",
            "### Secondary licences inside those imports",
            "",
            "An MIT upstream can still redistribute files under a different licence. These are they.",
            "",
            "| Files | Licence | Copyright | Licence text |",
            "| --- | --- | --- | --- |",
        ]
        for src, entry in extras:
            out.append(
                f"| `{src['dest']}/{entry['path']}` | {entry['license']} | "
                f"{entry.get('copyright','see licence text')} | "
                f"[`{src['dest']}/{entry['license_file']}`](./{src['dest']}/{entry['license_file']}) |"
            )

    out += [
        "",
        "## Tier 2: imported before the manifest existed",
        "",
        "Hand-copied into the tree before `scripts/sync_vendor.py` existed. Each is attributed and",
        "most carry a licence file in place, but none is commit-pinned or automatically refreshed.",
        "Migrating them to tier 1 is item 5 of the backlog in",
        "[`docs/ARCHITECTURE_REVIEW.md`](./docs/ARCHITECTURE_REVIEW.md). The inventory behind this",
        "table is [`docs/third-party-inventory.json`](./docs/third-party-inventory.json), and",
        "[`scripts/audit_third_party.py`](./scripts/audit_third_party.py) fails CI if a licence or",
        "attribution file appears in the tree without a matching entry.",
        "",
        "| Upstream project | Author | Licence | Vendored to | Local notice |",
        "| --- | --- | --- | --- | --- |",
    ]
    for entry in sorted(inventory.get("legacy", []), key=lambda e: e["name"].lower()):
        repo = entry.get("repo", "")
        name = f"[{entry['name']}]({repo})" if repo else entry["name"]
        paths = ", ".join(f"`{p}`" for p in entry["paths"][:3])
        if len(entry["paths"]) > 3:
            paths += f" and {len(entry['paths']) - 3} more"
        notice = entry.get("notice")
        notice_cell = f"[{os.path.basename(notice)}](./{notice})" if notice else "see prose in the skill"
        out.append(
            f"| {name} | {entry.get('author','see upstream')} | {entry.get('license','see upstream')} "
            f"| {paths} | {notice_cell} |"
        )

    out += [
        "",
        "## If an attribution here is wrong",
        "",
        "Open an issue and it gets corrected. Attribution reports are handled before anything else",
        "in this repository. If you are an author listed above and want your work removed, say so",
        "and it will be removed.",
        "",
    ]
    return "\n".join(out)


# ----------------------------------------------------------------------- core


def path_specs(source: dict) -> list:
    """Normalise and safety-check a source's declared paths."""
    specs = source.get("paths")
    if not specs:
        _fail(f"[{source.get('id')}] manifest source declares no `paths`")
    sid = source["id"]
    out = []
    for spec in specs:
        kind = spec.get("kind", SKILL_COLLECTION)
        if kind not in (SKILL_COLLECTION, SUPPORT):
            _fail(f"[{sid}] unknown path kind `{kind}`")
        out.append(
            {
                "from": safe_segment(spec.get("from", ""), "paths[].from", sid),
                "to": safe_segment(spec.get("to", ""), "paths[].to", sid),
                "kind": kind,
                "include": spec.get("include"),
                "file_include": spec.get("file_include"),
                "exclude": spec.get("exclude", []),
                "exclude_reasons": spec.get("exclude_reasons", {}),
            }
        )

    # Overlapping destinations let one mapping delete a tree owned by another.
    for i, a in enumerate(out):
        for j, b in enumerate(out):
            if i >= j:
                continue
            pa, pb = a["to"], b["to"]
            if pa == pb:
                _fail(f"[{sid}] two paths map to the same destination `{pa or '.'}`")
            if pa == "" or pb == "" or pb.startswith(pa + "/") or pa.startswith(pb + "/"):
                _fail(
                    f"[{sid}] destinations `{pa or '.'}` and `{pb or '.'}` overlap. Nested or "
                    f"root-level mappings alongside siblings let one mapping delete another's "
                    f"content. Give each mapping its own subdirectory."
                )
    return out


def process_source(source: dict, checkout: Path, sha: str, apply: bool) -> dict:
    sid = source["id"]
    dest_rel = safe_segment(source.get("dest", ""), "dest", sid)
    if not dest_rel:
        _fail(f"[{sid}] `dest` is required")
    dest_root = resolve_under(REPO_ROOT, dest_rel, "dest", sid)
    plan = path_specs(source)
    added, removed, changed = [], [], []
    owned = []

    for spec in plan:
        upstream = resolve_under(checkout, spec["from"], "paths[].from", sid)
        if not upstream.is_dir():
            _fail(f"[{sid}] upstream path not found: {spec['from'] or '<root>'}")
        assert_no_symlinks(upstream, sid, spec["from"] or ".")
        local = resolve_under(dest_root, spec["to"], "paths[].to", sid)
        label = spec["to"] or "."

        if spec["kind"] == SKILL_COLLECTION:
            selected = _selected(_child_dirs(upstream), spec["include"], spec["exclude"])
            spec["selected"] = selected
            spec["with_skill"] = [n for n in selected if _has_skill(upstream / n)]
            owned += [posixpath.join(spec["to"], n) if spec["to"] else n for n in selected]
            existing = _child_dirs(local)
            added += [f"{label}/{n}" for n in selected if n not in existing]
            changed += [
                f"{label}/{n}"
                for n in selected
                if n in existing and tree_digest(local / n) != tree_digest(upstream / n)
            ]
            if apply:
                for name in selected:
                    target = local / name
                    if target.exists():
                        shutil.rmtree(target)
                    _copy_tree(upstream / name, target)
                    upstream_path = posixpath.join(spec["from"], name) if spec["from"] else name
                    kind_label = "skill" if _has_skill(target) else "shared support directory"
                    _write(
                        target / "PROVENANCE.md",
                        provenance_text(source, upstream_path, target, sha, kind_label),
                    )
        else:
            spec["selected"] = []
            spec["with_skill"] = []
            owned.append(spec["to"])
            if tree_digest(local) != tree_digest(upstream):
                changed.append(f"{label}/ (support tree)")
            if apply:
                if local.exists():
                    shutil.rmtree(local)
                _copy_tree(upstream, local, file_include=spec.get("file_include"))
                _write(
                    local / "PROVENANCE.md",
                    provenance_text(
                        source,
                        spec["from"] or ".",
                        local,
                        sha,
                        "support files, linked to by the skills",
                    ),
                )

    # Anything the previous run owned and this one does not is deleted. Ownership
    # is read from the record on disk, never inferred from sibling directories.
    previously = read_ownership(dest_root)
    orphans = [p for p in previously if p not in owned]
    for orphan in sorted(orphans):
        target = resolve_under(dest_root, orphan, "previously owned path", sid)
        if target.exists():
            removed.append(f"{orphan} (no longer in the manifest)")
            if apply:
                shutil.rmtree(target)

    all_skills = [n for spec in plan for n in spec.get("with_skill", [])]
    all_selected = [n for spec in plan for n in spec.get("selected", [])]
    missing_mandatory = [m for m in (source.get("mandatory") or []) if m not in all_selected]

    if apply:
        lic = source.get("license_path")
        if not lic:
            _fail(f"[{sid}] `license_path` is required: a redistributed licence must be copied")
        if not (checkout / lic).exists():
            _fail(f"[{sid}] declared license_path `{lic}` not found upstream")
        _write(
            dest_root / "LICENSE.upstream",
            f"Vendored from {source['repo']} at commit {sha}.\n"
            f"Original licence text follows, unmodified.\n"
            f"{'-' * 76}\n\n" + (checkout / lic).read_text(encoding="utf-8"),
        )
        for entry in source.get("additional_licenses") or []:
            src_file = checkout / entry["upstream_license_file"]
            if not src_file.exists():
                _fail(f"[{sid}] additional licence file `{entry['upstream_license_file']}` not found")
            shutil.copy2(src_file, dest_root / entry["license_file"], follow_symlinks=False)
        _write(dest_root / "ATTRIBUTION.md", attribution_text(source, sha, plan))
        write_ownership(dest_root, owned, sid)

    return {
        "id": sid,
        "dest": source["dest"],
        "pinned_commit": source.get("pinned_commit"),
        "upstream_commit": sha,
        "commit_moved": source.get("pinned_commit") != sha,
        "skills": len(all_skills),
        "selected_directories": len(all_selected),
        "added": sorted(added),
        "removed": sorted(removed),
        "changed": sorted(changed),
        "missing_mandatory": missing_mandatory,
    }


def validate_manifest(manifest: dict) -> list:
    """Offline invariants. Fast enough to gate every pull request.

    Deliberately limited. This proves the tree matches what the manifest claims,
    that provenance and licence copies exist, and that nothing excluded slipped
    back in. It does not and cannot prove that an upstream had the right to
    license what it published, or that a declared author is the real one. Do not
    describe it as licence verification.
    """
    problems = []
    seen_ids, seen_dests = set(), set()

    for src in manifest.get("sources", []):
        sid = src.get("id", "<missing id>")
        for field in (
            "id",
            "name",
            "repo",
            "author",
            "license",
            "license_path",
            "dest",
            "pinned_commit",
            "paths",
        ):
            if not src.get(field):
                problems.append(f"[{sid}] source is missing required field `{field}`")
        if sid in seen_ids:
            problems.append(f"[{sid}] duplicate manifest source id")
        seen_ids.add(sid)

        dest = (src.get("dest") or "").strip("/")
        if dest in seen_dests:
            problems.append(f"[{sid}] two sources vendor into the same dest `{dest}`")
        seen_dests.add(dest)

        sha = src.get("pinned_commit", "")
        if sha and not SHA_RE.match(sha):
            problems.append(f"[{sid}] pinned_commit must be a full 40-char sha, got `{sha}`")

        dest_root = REPO_ROOT / dest
        if not dest_root.is_dir():
            problems.append(f"[{sid}] dest `{dest}` does not exist; run --sync")
            continue
        for required in ("ATTRIBUTION.md", "LICENSE.upstream", OWNERSHIP_FILE):
            if not (dest_root / required).exists():
                problems.append(f"[{sid}] `{dest}/{required}` is missing; run --sync")
        for entry in src.get("additional_licenses") or []:
            if not (dest_root / entry.get("license_file", "")).exists():
                problems.append(
                    f"[{sid}] additional licence text `{dest}/{entry.get('license_file')}` is "
                    f"missing, but the manifest says files here are under {entry.get('license')}"
                )

        if not src.get("paths"):
            continue
        specs = path_specs(src)
        skills_found = []
        expected_owned = set()
        for spec in specs:
            local = dest_root / spec["to"] if spec["to"] else dest_root
            for name in spec.get("exclude") or []:
                if name not in (spec.get("exclude_reasons") or {}):
                    problems.append(
                        f"[{sid}] `{spec['from']}/{name}` is excluded with no reason recorded"
                    )
            for name in spec.get("exclude_reasons") or {}:
                if name not in (spec.get("exclude") or []):
                    problems.append(
                        f"[{sid}] exclude_reasons documents `{name}` but exclude omits it"
                    )
            if not local.is_dir():
                problems.append(f"[{sid}] mapped path `{dest}/{spec['to']}` missing; run --sync")
                continue

            if spec["kind"] == SKILL_COLLECTION:
                for name in _child_dirs(local):
                    child = local / name
                    expected_owned.add(posixpath.join(spec["to"], name) if spec["to"] else name)
                    if _has_skill(child):
                        skills_found.append(name)
                        if not (child / "PROVENANCE.md").exists():
                            problems.append(
                                f"[{sid}] `{dest}/{spec['to']}/{name}` has no PROVENANCE.md; run --sync"
                            )
                    if any(fnmatch.fnmatch(name, p) for p in spec.get("exclude", [])):
                        problems.append(
                            f"[{sid}] `{dest}/{spec['to']}/{name}` is present but excluded"
                        )
            else:
                expected_owned.add(spec["to"])
                if not (local / "PROVENANCE.md").exists():
                    problems.append(
                        f"[{sid}] support tree `{dest}/{spec['to']}` has no PROVENANCE.md; run --sync"
                    )

        recorded = set(read_ownership(dest_root))
        for stale in sorted(recorded - expected_owned):
            problems.append(
                f"[{sid}] `{dest}/{OWNERSHIP_FILE}` still claims `{stale}`, which the manifest no "
                f"longer maps; run --sync to remove it"
            )
        for unrecorded in sorted(expected_owned - recorded):
            problems.append(
                f"[{sid}] `{dest}/{unrecorded}` is present but not recorded as owned; run --sync"
            )

        for name in src.get("mandatory") or []:
            if name not in skills_found:
                problems.append(f"[{sid}] mandatory skill `{name}` is not vendored into `{dest}`")

    if not NOTICES_PATH.exists():
        problems.append("THIRD_PARTY_NOTICES.md is missing; run --sync")
    else:
        notices = NOTICES_PATH.read_text(encoding="utf-8")
        for src in manifest.get("sources", []):
            if src.get("pinned_commit") and src["pinned_commit"] not in notices:
                problems.append(
                    f"[{src.get('id')}] THIRD_PARTY_NOTICES.md does not cite the pinned commit; run --sync"
                )
    return problems


def main(argv: list) -> int:
    ap = argparse.ArgumentParser(description="Import and refresh vendored upstream content.")
    mode = ap.add_mutually_exclusive_group(required=True)
    mode.add_argument(
        "--validate-manifest",
        action="store_true",
        help="offline check that the tree still matches the manifest",
    )
    mode.add_argument("--check", action="store_true", help="report upstream drift, write nothing")
    mode.add_argument("--sync", action="store_true", help="apply upstream into the working tree")
    ap.add_argument("--source", action="append", help="limit to a manifest source id (repeatable)")
    ap.add_argument("--output", choices=("text", "json"), default="text")
    args = ap.parse_args(argv)

    manifest = load_manifest()

    if args.validate_manifest:
        problems = validate_manifest(manifest)
        if args.output == "json":
            print(json.dumps({"ok": not problems, "problems": problems}, indent=2))
        else:
            for problem in problems:
                print(f"error: {problem}")
            print()
            print(
                f"{len(manifest.get('sources', []))} vendored source(s) checked, "
                f"{len(problems)} problem(s)"
            )
        return 1 if problems else 0

    if not shutil.which("git"):
        _fail("git is required and was not found on PATH")

    sources = manifest.get("sources", [])
    if args.source:
        sources = [s for s in sources if s["id"] in args.source]
        if not sources:
            _fail(f"no manifest source matched {args.source}")
    if not sources:
        _fail("manifest declares no sources")

    results = []
    with tempfile.TemporaryDirectory(prefix="vendor-sync-") as tmp:
        for source in sources:
            checkout, sha = fetch_upstream(source, Path(tmp))
            results.append(process_source(source, checkout, sha, apply=args.sync))
            if args.sync:
                source["pinned_commit"] = sha
                source["pinned_at"] = _dt.date.today().isoformat()

    if args.sync:
        MANIFEST_PATH.write_text(
            json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
        )
        _write(NOTICES_PATH, notices_text(manifest))

    blocked = [r for r in results if r["missing_mandatory"]]
    drift = [r for r in results if r["added"] or r["removed"] or r["changed"] or r["commit_moved"]]

    if args.output == "json":
        print(
            json.dumps(
                {
                    "mode": "sync" if args.sync else "check",
                    "drift": bool(drift),
                    "blocked": bool(blocked),
                    "sources": results,
                },
                indent=2,
            )
        )
    else:
        for r in results:
            print(f"[{r['id']}] -> {r['dest']}")
            print(
                f"  upstream commit    : {r['upstream_commit'][:12]}"
                + ("  (moved)" if r["commit_moved"] else "  (unchanged)")
            )
            print(
                f"  skills             : {r['skills']}"
                f"   (from {r['selected_directories']} selected directories)"
            )
            for key in ("added", "removed", "changed"):
                if r[key]:
                    print(f"  {key:<18} : {', '.join(r[key])}")
            if r["missing_mandatory"]:
                print(f"  MANDATORY MISSING  : {', '.join(r['missing_mandatory'])}")
        print()
        if args.sync:
            print("drift applied" if drift else "nothing to apply")
        else:
            print("drift detected" if drift else "no drift detected")

    if blocked:
        print(
            "error: a skill listed as mandatory is absent from the selection; "
            "fix include/exclude in skills/vendor.manifest.json",
            file=sys.stderr,
        )
        return 1
    if args.check and drift:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
