#!/usr/bin/env python3
"""Import and refresh vendored upstream skills.

One code path serves both jobs. The first import of an upstream project and the
scheduled refresh two weeks later run exactly the same function, so a vendored
directory can never drift into a hand-maintained fork by accident.

Reads skills/vendor.manifest.json. Standard library only.

    scripts/sync_vendor.py --validate-manifest  # offline consistency check, used by CI
    scripts/sync_vendor.py --check              # report drift vs upstream, write nothing
    scripts/sync_vendor.py --sync               # apply upstream into the tree
    scripts/sync_vendor.py --sync --source pstack
    scripts/sync_vendor.py --check --output json

--validate-manifest needs no network, so it can gate every pull request. --check
and --sync clone upstream and belong in the scheduled refresh, where an upstream
commit moving is news rather than a broken build.

Exit codes
    0  no drift (--check), sync applied cleanly (--sync), or manifest consistent
    1  drift detected, inconsistent manifest, or a mandatory skill is missing
    2  usage or environment error
"""

from __future__ import annotations

import argparse
import datetime as _dt
import fnmatch
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
MANIFEST_PATH = REPO_ROOT / "skills" / "vendor.manifest.json"
NOTICES_PATH = REPO_ROOT / "THIRD_PARTY_NOTICES.md"
GENERATED_BANNER = "<!-- generated by scripts/sync_vendor.py -- do not edit by hand -->"


# --------------------------------------------------------------------------- io


def _fail(msg: str, code: int = 2) -> "None":
    print(f"error: {msg}", file=sys.stderr)
    raise SystemExit(code)


def _run(args: list, cwd: "Path | None" = None) -> str:
    proc = subprocess.run(
        args, cwd=str(cwd) if cwd else None, capture_output=True, text=True
    )
    if proc.returncode != 0:
        _fail(f"command failed: {' '.join(args)}\n{proc.stderr.strip()}")
    return proc.stdout.strip()


def load_manifest() -> dict:
    if not MANIFEST_PATH.exists():
        _fail(f"missing manifest: {MANIFEST_PATH}")
    try:
        return json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        _fail(f"manifest is not valid JSON: {exc}")


def _write(path: Path, text: str) -> bool:
    """Write only when content changes. Returns True when the file changed."""
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == text:
        return False
    path.write_text(text, encoding="utf-8")
    return True


# ---------------------------------------------------------------- fingerprints


def tree_digest(root: Path) -> str:
    """Order-stable digest of a directory's tracked content.

    Provenance and attribution files are excluded because this repository
    generates them; including them would make every tree look permanently
    dirty against upstream.
    """
    if not root.exists():
        return ""
    generated = {"PROVENANCE.md"}
    entries = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = sorted(d for d in dirnames if d != ".git")
        for name in sorted(filenames):
            if name in generated:
                continue
            full = Path(dirpath) / name
            rel = full.relative_to(root).as_posix()
            entries.append((rel, hashlib.sha256(full.read_bytes()).hexdigest()))
    h = hashlib.sha256()
    for rel, digest in sorted(entries):
        h.update(rel.encode("utf-8") + b"\0" + digest.encode("ascii") + b"\n")
    return h.hexdigest()


def _selected(names: list, include: list, exclude: list) -> list:
    keep = []
    for name in sorted(names):
        if not any(fnmatch.fnmatch(name, pat) for pat in include or ["*"]):
            continue
        if any(fnmatch.fnmatch(name, pat) for pat in exclude or []):
            continue
        keep.append(name)
    return keep


# ------------------------------------------------------------------- upstream


def fetch_upstream(source: dict, workdir: Path) -> "tuple[Path, str]":
    """Clone the upstream repo at the manifest ref. Returns (checkout, sha)."""
    ref = source.get("ref") or "HEAD"
    dest = workdir / source["id"]
    _run(["git", "clone", "--quiet", "--depth", "1", "--branch", ref, source["repo"], str(dest)])
    sha = _run(["git", "rev-parse", "HEAD"], cwd=dest)
    return dest, sha


# ------------------------------------------------------------------ rendering


def provenance_text(source: dict, skill: str, sha: str) -> str:
    repo = source["repo"].rstrip("/")
    sub = source.get("source_subpath", "").strip("/")
    upstream_path = f"{sub}/{skill}" if sub else skill
    permalink = f"{repo}/tree/{sha}/{upstream_path}"
    lines = [
        GENERATED_BANNER,
        "",
        f"# Provenance: `{skill}`",
        "",
        f"This directory is vendored, unmodified, from an upstream project. Do not edit it here.",
        "",
        f"| Field | Value |",
        f"| --- | --- |",
        f"| Upstream project | [{source['name']}]({repo}) |",
        f"| Upstream path | `{upstream_path}` |",
        f"| Pinned commit | [`{sha[:12]}`]({repo}/commit/{sha}) |",
        f"| Permalink | {permalink} |",
        f"| Original author | {source.get('author', 'see upstream')} |",
        f"| Upstream licence | {source.get('license', 'see upstream')} |",
        f"| Licence copy | [`../LICENSE.upstream`](../LICENSE.upstream) |",
        f"| Full attribution | [`../ATTRIBUTION.md`](../ATTRIBUTION.md) |",
        f"| Refresh cadence | Automated every two weeks by [`.github/workflows/sync-vendored-skills.yml`](../../../.github/workflows/sync-vendored-skills.yml) |",
    ]
    if source.get("upstream_of_upstream"):
        lines.append(
            f"| Upstream's own source | {source['upstream_of_upstream']} |"
        )
    lines += [
        "",
        "## Changing this skill",
        "",
        "Send the change to the upstream project. If this repository must diverge, remove the",
        f"skill from `include` in [`skills/vendor.manifest.json`](../../vendor.manifest.json), copy it to a",
        "non-vendored path, and record why in `ATTRIBUTION.md`. Local edits made in place are",
        "silently reverted by the next scheduled sync.",
        "",
    ]
    return "\n".join(lines)


def attribution_text(source: dict, sha: str, skills: list, excluded: dict) -> str:
    repo = source["repo"].rstrip("/")
    out = [
        GENERATED_BANNER,
        "",
        f"# Attribution: {source['name']}",
        "",
        f"Every skill in this directory was copied from [{source['name']}]({repo}) at commit",
        f"[`{sha}`]({repo}/commit/{sha}), pinned on {source.get('pinned_at', 'n/a')}.",
        "",
        f"- **Upstream project:** <{repo}>",
        f"- **Original author:** {source.get('author', 'see upstream')}",
        f"- **Upstream licence:** {source.get('license', 'see upstream')}, reproduced verbatim in [`LICENSE.upstream`](./LICENSE.upstream)",
        f"- **Tracked by:** [`skills/vendor.manifest.json`](../vendor.manifest.json)",
        f"- **Refreshed by:** [`scripts/sync_vendor.py`](../../scripts/sync_vendor.py), run every two weeks by [`.github/workflows/sync-vendored-skills.yml`](../../.github/workflows/sync-vendored-skills.yml)",
    ]
    if source.get("upstream_of_upstream"):
        out.append(
            f"- **Upstream's own source:** {source['upstream_of_upstream']} (pstack is a mirror kept in sync for standalone use)"
        )
    out += [
        "",
        "No functional changes were made to the vendored content. This repository adds only a",
        "`PROVENANCE.md` inside each skill directory and this file.",
        "",
        f"## Imported skills ({len(skills)})",
        "",
        "| Skill | Upstream permalink |",
        "| --- | --- |",
    ]
    sub = source.get("source_subpath", "").strip("/")
    for skill in skills:
        p = f"{sub}/{skill}" if sub else skill
        out.append(f"| [`{skill}`](./{skill}/) | [`{p}`]({repo}/tree/{sha}/{p}) |")

    mandatory = source.get("mandatory") or []
    if mandatory:
        out += [
            "",
            "## Mandatory imports",
            "",
            source.get("mandatory_reason", ""),
            "",
        ]
        for m in mandatory:
            out.append(f"- [`{m}`](./{m}/)")

    if excluded:
        out += [
            "",
            "## Deliberate exclusions",
            "",
            "Upstream skills left out of this repository, and why. Recorded so the decision is",
            "auditable rather than looking like an incomplete import.",
            "",
            "| Upstream skill | Reason |",
            "| --- | --- |",
        ]
        for name in sorted(excluded):
            out.append(f"| `{name}` | {excluded[name]} |")

    if source.get("notes"):
        out += ["", "## Notes", "", source["notes"]]
    out.append("")
    return "\n".join(out)


def notices_text(manifest: dict) -> str:
    out = [
        GENERATED_BANNER,
        "",
        "# Third-party notices",
        "",
        "This repository redistributes work from the upstream projects below. Each entry keeps its",
        "original licence, its original copyright, and a commit-pinned link back to the source.",
        "Automated refreshes are tracked in [`skills/vendor.manifest.json`](./skills/vendor.manifest.json).",
        "",
        "| Upstream project | Author | Licence | Vendored to | Pinned commit | Attribution |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for src in manifest.get("sources", []):
        repo = src["repo"].rstrip("/")
        sha = src.get("pinned_commit", "")
        short = f"[`{sha[:12]}`]({repo}/commit/{sha})" if sha else "unpinned"
        out.append(
            f"| [{src['name']}]({repo}) | {src.get('author','see upstream')} | "
            f"{src.get('license','see upstream')} | `{src['dest']}/` | {short} | "
            f"[ATTRIBUTION.md](./{src['dest']}/ATTRIBUTION.md) |"
        )
    out += [
        "",
        "## Imports predating the manifest",
        "",
        "These were imported by hand before `scripts/sync_vendor.py` existed. They are attributed",
        "but not yet under automated refresh. Migrating them is tracked in",
        "[`docs/ARCHITECTURE_REVIEW.md`](./docs/ARCHITECTURE_REVIEW.md).",
        "",
        "| Upstream project | Author | Licence | Vendored to | Attribution |",
        "| --- | --- | --- | --- | --- |",
        "| [alirezarezvani-claude-skills](https://github.com/borahanmirzaii/alirezarezvani-claude-skills) "
        "| Alireza Rezvani and contributors | MIT | 18 domains under `skills/` "
        "| [ALIREZAREZVANI_CLAUDE_SKILLS_ATTRIBUTION.md](./skills/ALIREZAREZVANI_CLAUDE_SKILLS_ATTRIBUTION.md) |",
        "| [stitch-skills](https://github.com/google-labs-code/stitch-skills) | Google Labs and contributors "
        "| see per-skill `LICENSE` | `skills/design/stitch-*`, `skills/engineering/stitch-*` "
        "| per-skill `ATTRIBUTION.md` |",
        "| [taste-skill and related](https://github.com/bughunt8/skills) | see per-skill `ATTRIBUTION.md` "
        "| see per-skill `LICENSE` | `skills/design/*` | per-skill `ATTRIBUTION.md` |",
        "| [prd-generator](https://github.com/jamesrochabrun/skills) | James Rochabrun | MIT "
        "| `skills/productivity/agile-prd-creator` | inline in [README.md](./README.md) |",
        "| [claude-skill-management-consultant-B1](https://github.com/DogInfantry/claude-skill-management-consultant-B1) "
        "| DogInfantry | Apache-2.0 | `skills/productivity/management-consultant` | inline in [README.md](./README.md) |",
        "",
        "Nothing here changes the licence of the original work. If you are an author listed above and",
        "an attribution is wrong, open an issue and it will be corrected.",
        "",
    ]
    return "\n".join(out)


# ----------------------------------------------------------------------- core


def process_source(source: dict, checkout: Path, sha: str, apply: bool) -> dict:
    sub = source.get("source_subpath", "").strip("/")
    upstream_root = checkout / sub if sub else checkout
    if not upstream_root.is_dir():
        _fail(f"[{source['id']}] upstream subpath not found: {sub or '<root>'}")

    upstream_names = sorted(
        d.name for d in upstream_root.iterdir() if d.is_dir() and not d.name.startswith(".")
    )
    selected = _selected(upstream_names, source.get("include", ["*"]), source.get("exclude", []))

    missing_mandatory = [m for m in (source.get("mandatory") or []) if m not in selected]

    dest_root = REPO_ROOT / source["dest"]
    existing = sorted(
        d.name
        for d in (dest_root.iterdir() if dest_root.is_dir() else [])
        if d.is_dir() and not d.name.startswith(".")
    )

    added = [n for n in selected if n not in existing]
    removed = [n for n in existing if n not in selected]
    changed = []
    for name in selected:
        if name in existing and tree_digest(dest_root / name) != tree_digest(upstream_root / name):
            changed.append(name)

    written = []
    if apply:
        for name in removed:
            shutil.rmtree(dest_root / name)
        for name in selected:
            target = dest_root / name
            if target.exists():
                shutil.rmtree(target)
            shutil.copytree(upstream_root / name, target, ignore=shutil.ignore_patterns(".git"))
            if _write(target / "PROVENANCE.md", provenance_text(source, name, sha)):
                written.append(str((target / "PROVENANCE.md").relative_to(REPO_ROOT)))

        lic_rel = source.get("license_path")
        if lic_rel and (checkout / lic_rel).exists():
            header = (
                f"Vendored from {source['repo']} at commit {sha}.\n"
                f"Original licence text follows, unmodified.\n"
                f"{'-' * 76}\n\n"
            )
            _write(
                dest_root / "LICENSE.upstream",
                header + (checkout / lic_rel).read_text(encoding="utf-8"),
            )

        _write(
            dest_root / "ATTRIBUTION.md",
            attribution_text(source, sha, selected, source.get("exclude_reasons", {})),
        )

    return {
        "id": source["id"],
        "dest": source["dest"],
        "pinned_commit": source.get("pinned_commit"),
        "upstream_commit": sha,
        "commit_moved": source.get("pinned_commit") != sha,
        "upstream_skill_count": len(upstream_names),
        "selected_count": len(selected),
        "added": added,
        "removed": removed,
        "changed": changed,
        "missing_mandatory": missing_mandatory,
        "generated": written,
    }


SHA_RE = re.compile(r"^[0-9a-f]{40}$")


def validate_manifest(manifest: dict) -> list:
    """Offline invariants. Fast enough to gate every pull request.

    Answers the question a reviewer actually has: does the tree still match what
    the manifest claims about it? No network, so an upstream commit moving does
    not turn every unrelated pull request red.
    """
    problems = []
    seen_ids, seen_dests = set(), set()

    for src in manifest.get("sources", []):
        sid = src.get("id", "<missing id>")
        for field in ("id", "name", "repo", "license", "dest", "pinned_commit"):
            if not src.get(field):
                problems.append(f"[{sid}] source is missing required field `{field}`")
        if sid in seen_ids:
            problems.append(f"[{sid}] duplicate manifest source id")
        seen_ids.add(sid)

        dest = (src.get("dest") or "").strip("/")
        if dest in seen_dests:
            problems.append(f"[{sid}] two sources vendor into the same dest `{dest}`")
        seen_dests.add(dest)

        sha = src.get("pinned_commit", "")
        if sha and not SHA_RE.match(sha):
            problems.append(f"[{sid}] pinned_commit must be a full 40-char sha, got `{sha}`")

        for name in src.get("exclude") or []:
            if name not in (src.get("exclude_reasons") or {}):
                problems.append(f"[{sid}] `{name}` is excluded with no reason in exclude_reasons")
        for name in src.get("exclude_reasons") or {}:
            if name not in (src.get("exclude") or []):
                problems.append(f"[{sid}] exclude_reasons documents `{name}` but exclude omits it")

        dest_root = REPO_ROOT / dest
        if not dest_root.is_dir():
            problems.append(f"[{sid}] dest `{dest}` does not exist; run --sync")
            continue

        for required in ("ATTRIBUTION.md", "LICENSE.upstream"):
            if not (dest_root / required).exists():
                problems.append(f"[{sid}] `{dest}/{required}` is missing; run --sync")

        present = sorted(
            d.name for d in dest_root.iterdir() if d.is_dir() and not d.name.startswith(".")
        )
        for name in present:
            if not (dest_root / name / "PROVENANCE.md").exists():
                problems.append(f"[{sid}] `{dest}/{name}` has no PROVENANCE.md; run --sync")
            if any(fnmatch.fnmatch(name, pat) for pat in src.get("exclude", [])):
                problems.append(f"[{sid}] `{dest}/{name}` is present but the manifest excludes it")
        for name in src.get("mandatory") or []:
            if name not in present:
                problems.append(f"[{sid}] mandatory skill `{name}` is not vendored into `{dest}`")

    if not NOTICES_PATH.exists():
        problems.append("THIRD_PARTY_NOTICES.md is missing; run --sync")
    else:
        notices = NOTICES_PATH.read_text(encoding="utf-8")
        for src in manifest.get("sources", []):
            if src.get("pinned_commit") and src["pinned_commit"] not in notices:
                problems.append(
                    f"[{src.get('id')}] THIRD_PARTY_NOTICES.md does not cite the pinned commit; run --sync"
                )
    return problems


def main(argv: list) -> int:
    ap = argparse.ArgumentParser(description="Import and refresh vendored upstream skills.")
    mode = ap.add_mutually_exclusive_group(required=True)
    mode.add_argument(
        "--validate-manifest",
        action="store_true",
        help="offline check that the tree still matches the manifest",
    )
    mode.add_argument("--check", action="store_true", help="report upstream drift, write nothing")
    mode.add_argument("--sync", action="store_true", help="apply upstream into the working tree")
    ap.add_argument("--source", action="append", help="limit to a manifest source id (repeatable)")
    ap.add_argument("--output", choices=("text", "json"), default="text")
    args = ap.parse_args(argv)

    if args.validate_manifest:
        manifest = load_manifest()
        problems = validate_manifest(manifest)
        if args.output == "json":
            print(json.dumps({"ok": not problems, "problems": problems}, indent=2))
        else:
            for problem in problems:
                print(f"error: {problem}")
            print()
            print(
                f"{len(manifest.get('sources', []))} vendored source(s) checked, "
                f"{len(problems)} problem(s)"
            )
        return 1 if problems else 0

    if not shutil.which("git"):
        _fail("git is required and was not found on PATH")

    manifest = load_manifest()
    sources = manifest.get("sources", [])
    if args.source:
        sources = [s for s in sources if s["id"] in args.source]
        if not sources:
            _fail(f"no manifest source matched {args.source}")
    if not sources:
        _fail("manifest declares no sources")

    results = []
    with tempfile.TemporaryDirectory(prefix="vendor-sync-") as tmp:
        workdir = Path(tmp)
        for source in sources:
            checkout, sha = fetch_upstream(source, workdir)
            res = process_source(source, checkout, sha, apply=args.sync)
            if args.sync:
                source["pinned_commit"] = sha
                source["pinned_at"] = _dt.date.today().isoformat()
            results.append(res)

    if args.sync:
        MANIFEST_PATH.write_text(
            json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
        )
        _write(NOTICES_PATH, notices_text(manifest))

    blocked = [r for r in results if r["missing_mandatory"]]
    drift = [
        r
        for r in results
        if r["added"] or r["removed"] or r["changed"] or r["commit_moved"]
    ]

    if args.output == "json":
        print(
            json.dumps(
                {
                    "mode": "sync" if args.sync else "check",
                    "drift": bool(drift),
                    "blocked": bool(blocked),
                    "sources": results,
                },
                indent=2,
            )
        )
    else:
        for r in results:
            print(f"[{r['id']}] -> {r['dest']}")
            print(f"  upstream commit : {r['upstream_commit'][:12]}"
                  + ("  (moved)" if r["commit_moved"] else "  (unchanged)"))
            print(f"  upstream skills : {r['upstream_skill_count']}  selected: {r['selected_count']}")
            for label, key in (("added", "added"), ("removed", "removed"), ("changed", "changed")):
                if r[key]:
                    print(f"  {label:<15} : {', '.join(r[key])}")
            if r["missing_mandatory"]:
                print(f"  MANDATORY MISSING: {', '.join(r['missing_mandatory'])}")
        verb = "applied" if args.sync else "detected"
        print()
        print(f"{'drift ' + verb if drift else 'no drift ' + ('applied' if args.sync else 'detected')}")

    if blocked:
        print(
            "error: a skill listed as mandatory is absent from the selection; "
            "fix include/exclude in skills/vendor.manifest.json",
            file=sys.stderr,
        )
        return 1
    if args.check and drift:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
