#!/usr/bin/env python3
"""Import and refresh vendored upstream skills.

One code path serves both jobs. The first import of an upstream project and the
scheduled refresh two weeks later run exactly the same function, so a vendored
directory cannot drift into a hand-maintained fork by accident.

Reads skills/vendor.manifest.json. Standard library only.

    scripts/sync_vendor.py --validate-manifest  # offline consistency check, used by CI
    scripts/sync_vendor.py --check              # report drift vs upstream, write nothing
    scripts/sync_vendor.py --sync               # apply upstream into the tree
    scripts/sync_vendor.py --sync --source pstack
    scripts/sync_vendor.py --check --output json

--validate-manifest needs no network, so it can gate every pull request. --check
and --sync clone upstream and belong in the scheduled refresh, where an upstream
commit moving is news rather than a broken build.

## Why a source declares `paths` rather than one subdirectory

The first vendored project kept everything under `skills/`. The second,
job-hunt-skills, has 47 links from its skills into a sibling `guides/` directory
and more into `templates/`. Copying only `skills/` produces a tree whose internal
links all point at nothing.

So a source maps a list of upstream subtrees into its own vendored root, and the
mapping preserves the relative distance between them. Two kinds:

    skill-collection  a directory of skill directories. Each selected child is
                      tracked individually, gets a PROVENANCE.md, and appears in
                      the added/removed/changed report.
    support           a subtree the skills link into. Copied whole, one
                      PROVENANCE.md at its root, no per-file tracking.

Exit codes
    0  no drift (--check), sync applied cleanly (--sync), or manifest consistent
    1  drift detected, inconsistent manifest, or a mandatory skill is missing
    2  usage or environment error
"""

from __future__ import annotations

import argparse
import datetime as _dt
import fnmatch
import hashlib
import json
import os
import posixpath
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
MANIFEST_PATH = REPO_ROOT / "skills" / "vendor.manifest.json"
NOTICES_PATH = REPO_ROOT / "THIRD_PARTY_NOTICES.md"
GENERATED_BANNER = "<!-- generated by scripts/sync_vendor.py -- do not edit by hand -->"
SHA_RE = re.compile(r"^[0-9a-f]{40}$")
SKILL_COLLECTION = "skill-collection"
SUPPORT = "support"


# --------------------------------------------------------------------------- io


def _fail(msg: str, code: int = 2):
    print(f"error: {msg}", file=sys.stderr)
    raise SystemExit(code)


def _run(args: list, cwd: "Path | None" = None) -> str:
    proc = subprocess.run(args, cwd=str(cwd) if cwd else None, capture_output=True, text=True)
    if proc.returncode != 0:
        _fail(f"command failed: {' '.join(args)}\n{proc.stderr.strip()}")
    return proc.stdout.strip()


def load_manifest() -> dict:
    if not MANIFEST_PATH.exists():
        _fail(f"missing manifest: {MANIFEST_PATH}")
    try:
        return json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        _fail(f"manifest is not valid JSON: {exc}")


def _write(path: Path, text: str) -> bool:
    """Write only when content changes. Returns True when the file changed."""
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == text:
        return False
    path.write_text(text, encoding="utf-8")
    return True


def _rel(from_dir: Path, to_path: Path) -> str:
    """Markdown-safe relative link between two paths inside the repository."""
    return os.path.relpath(to_path, from_dir).replace(os.sep, "/")


# ---------------------------------------------------------------- fingerprints


def tree_digest(root: Path) -> str:
    """Order-stable digest of a directory's content.

    PROVENANCE.md is excluded because this repository generates it. Including it
    would make every vendored tree look permanently different from upstream.
    """
    if not root.exists():
        return ""
    entries = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = sorted(d for d in dirnames if d != ".git")
        for name in sorted(filenames):
            if name == "PROVENANCE.md":
                continue
            full = Path(dirpath) / name
            rel = full.relative_to(root).as_posix()
            entries.append((rel, hashlib.sha256(full.read_bytes()).hexdigest()))
    digest = hashlib.sha256()
    for rel, file_hash in sorted(entries):
        digest.update(rel.encode("utf-8") + b"\0" + file_hash.encode("ascii") + b"\n")
    return digest.hexdigest()


def _selected(names: list, include: list, exclude: list) -> list:
    keep = []
    for name in sorted(names):
        if not any(fnmatch.fnmatch(name, pat) for pat in include or ["*"]):
            continue
        if any(fnmatch.fnmatch(name, pat) for pat in exclude or []):
            continue
        keep.append(name)
    return keep


def _child_dirs(root: Path) -> list:
    if not root.is_dir():
        return []
    return sorted(d.name for d in root.iterdir() if d.is_dir() and not d.name.startswith("."))


def _has_skill(path: Path) -> bool:
    return (path / "SKILL.md").is_file()


# ------------------------------------------------------------------- upstream


def fetch_upstream(source: dict, workdir: Path) -> "tuple[Path, str]":
    ref = source.get("ref") or "HEAD"
    dest = workdir / source["id"]
    _run(
        ["git", "clone", "--quiet", "--depth", "1", "--branch", ref, source["repo"], str(dest)]
    )
    return dest, _run(["git", "rev-parse", "HEAD"], cwd=dest)


# ------------------------------------------------------------------ rendering


def provenance_text(source: dict, upstream_path: str, local_dir: Path, sha: str, kind: str) -> str:
    repo = source["repo"].rstrip("/")
    dest_root = REPO_ROOT / source["dest"]
    permalink = f"{repo}/tree/{sha}/{upstream_path}"
    label = local_dir.name

    rows = [
        f"| Upstream project | [{source['name']}]({repo}) |",
        f"| Upstream path | `{upstream_path}` |",
        f"| Pinned commit | [`{sha[:12]}`]({repo}/commit/{sha}) |",
        f"| Permalink | {permalink} |",
        f"| Original author | {source.get('author', 'see upstream')} |",
        f"| Upstream licence | {source.get('license', 'see upstream')} |",
        f"| Licence copy | [`{_rel(local_dir, dest_root / 'LICENSE.upstream')}`]"
        f"({_rel(local_dir, dest_root / 'LICENSE.upstream')}) |",
        f"| Full attribution | [`{_rel(local_dir, dest_root / 'ATTRIBUTION.md')}`]"
        f"({_rel(local_dir, dest_root / 'ATTRIBUTION.md')}) |",
        f"| Content kind | {kind} |",
        "| Refresh cadence | Automated every two weeks by "
        f"[`{_rel(local_dir, REPO_ROOT / '.github/workflows/sync-vendored-skills.yml')}`]"
        f"({_rel(local_dir, REPO_ROOT / '.github/workflows/sync-vendored-skills.yml')}) |",
    ]
    if source.get("upstream_of_upstream"):
        rows.append(f"| Upstream's own source | {source['upstream_of_upstream']} |")

    manifest_link = _rel(local_dir, MANIFEST_PATH)
    return "\n".join(
        [
            GENERATED_BANNER,
            "",
            f"# Provenance: `{label}`",
            "",
            "This directory is vendored, unmodified, from an upstream project. Do not edit it here.",
            "",
            "| Field | Value |",
            "| --- | --- |",
            *rows,
            "",
            "## Changing this",
            "",
            "Send the change to the upstream project. If this repository must diverge, remove the",
            f"entry from [`{manifest_link}`]({manifest_link}), copy it to a non-vendored path, and",
            "record why in the collection's `ATTRIBUTION.md`. Local edits made in place are silently",
            "reverted by the next scheduled sync.",
            "",
        ]
    )


def attribution_text(source: dict, sha: str, plan: list) -> str:
    repo = source["repo"].rstrip("/")
    dest_root = REPO_ROOT / source["dest"]
    out = [
        GENERATED_BANNER,
        "",
        f"# Attribution: {source['name']}",
        "",
        f"Everything in this directory was copied from [{source['name']}]({repo}) at commit",
        f"[`{sha}`]({repo}/commit/{sha}), pinned on {source.get('pinned_at', 'n/a')}.",
        "",
        f"- **Upstream project:** <{repo}>",
        f"- **Original author:** {source.get('author', 'see upstream')}",
        f"- **Upstream licence:** {source.get('license', 'see upstream')}, reproduced verbatim in "
        "[`LICENSE.upstream`](./LICENSE.upstream)",
        f"- **Tracked by:** [`{_rel(dest_root, MANIFEST_PATH)}`]({_rel(dest_root, MANIFEST_PATH)})",
        "- **Refreshed by:** "
        f"[`{_rel(dest_root, REPO_ROOT / 'scripts/sync_vendor.py')}`]"
        f"({_rel(dest_root, REPO_ROOT / 'scripts/sync_vendor.py')}), run every two weeks by "
        f"[`{_rel(dest_root, REPO_ROOT / '.github/workflows/sync-vendored-skills.yml')}`]"
        f"({_rel(dest_root, REPO_ROOT / '.github/workflows/sync-vendored-skills.yml')})",
    ]
    if source.get("upstream_of_upstream"):
        out.append(f"- **Upstream's own source:** {source['upstream_of_upstream']}")
    out += [
        "",
        "No functional changes were made to the vendored content. This repository adds only a",
        "`PROVENANCE.md` per vendored directory and this file.",
        "",
        "## Layout",
        "",
        "Upstream subtrees are mapped so that the relative links inside them keep resolving.",
        "",
        "| Upstream path | Vendored to | Kind |",
        "| --- | --- | --- |",
    ]
    for spec in plan:
        out.append(
            f"| `{spec['from'] or '.'}` | [`{spec['to'] or '.'}/`](./{spec['to']}/) | {spec['kind']} |"
        )

    for spec in plan:
        if spec["kind"] != SKILL_COLLECTION:
            continue
        out += [
            "",
            f"## Imported skills from `{spec['from']}` ({len(spec['selected'])})",
            "",
            "| Skill | Upstream permalink |",
            "| --- | --- |",
        ]
        for name in spec["selected"]:
            upstream_path = posixpath.join(spec["from"], name) if spec["from"] else name
            local = posixpath.join(spec["to"], name) if spec["to"] else name
            out.append(
                f"| [`{name}`](./{local}/) | [`{upstream_path}`]({repo}/tree/{sha}/{upstream_path}) |"
            )

    mandatory = source.get("mandatory") or []
    if mandatory:
        out += ["", "## Mandatory imports", "", source.get("mandatory_reason", ""), ""]
        for name in mandatory:
            out.append(f"- `{name}`")

    reasons = {}
    for spec in plan:
        reasons.update(spec.get("exclude_reasons") or {})
    if reasons:
        out += [
            "",
            "## Deliberate exclusions",
            "",
            "Upstream content left out of this repository, and why. Recorded so the decision is",
            "auditable rather than looking like an incomplete import.",
            "",
            "| Upstream path | Reason |",
            "| --- | --- |",
        ]
        for name in sorted(reasons):
            out.append(f"| `{name}` | {reasons[name]} |")

    if source.get("limitations"):
        out += ["", "## Known limitations of this import", ""]
        for item in source["limitations"]:
            out.append(f"- {item}")

    if source.get("notes"):
        out += ["", "## Notes", "", source["notes"]]
    out.append("")
    return "\n".join(out)


def notices_text(manifest: dict) -> str:
    out = [
        GENERATED_BANNER,
        "",
        "# Third-party notices",
        "",
        "This repository redistributes work from the upstream projects below. Each entry keeps its",
        "original licence, its original copyright, and a commit-pinned link back to the source.",
        "Automated refreshes are tracked in [`skills/vendor.manifest.json`](./skills/vendor.manifest.json).",
        "",
        "| Upstream project | Author | Licence | Vendored to | Pinned commit | Attribution |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for src in manifest.get("sources", []):
        repo = src["repo"].rstrip("/")
        sha = src.get("pinned_commit", "")
        short = f"[`{sha[:12]}`]({repo}/commit/{sha})" if sha else "unpinned"
        out.append(
            f"| [{src['name']}]({repo}) | {src.get('author','see upstream')} | "
            f"{src.get('license','see upstream')} | `{src['dest']}/` | {short} | "
            f"[ATTRIBUTION.md](./{src['dest']}/ATTRIBUTION.md) |"
        )
    out += [
        "",
        "## Imports predating the manifest",
        "",
        "These were imported by hand before `scripts/sync_vendor.py` existed. They are attributed",
        "but not yet under automated refresh. Migrating them is item 5 of the backlog in",
        "[`docs/ARCHITECTURE_REVIEW.md`](./docs/ARCHITECTURE_REVIEW.md).",
        "",
        "| Upstream project | Author | Licence | Vendored to | Attribution |",
        "| --- | --- | --- | --- | --- |",
        "| [alirezarezvani-claude-skills](https://github.com/borahanmirzaii/alirezarezvani-claude-skills) "
        "| Alireza Rezvani and contributors | MIT | 18 domains under `skills/` "
        "| [ALIREZAREZVANI_CLAUDE_SKILLS_ATTRIBUTION.md](./skills/ALIREZAREZVANI_CLAUDE_SKILLS_ATTRIBUTION.md) |",
        "| [stitch-skills](https://github.com/google-labs-code/stitch-skills) | Google Labs and contributors "
        "| see per-skill `LICENSE` | `skills/design/stitch-*`, `skills/engineering/stitch-*` "
        "| per-skill `ATTRIBUTION.md` |",
        "| [taste-skill and related](https://github.com/bughunt8/skills) | see per-skill `ATTRIBUTION.md` "
        "| see per-skill `LICENSE` | `skills/design/*` | per-skill `ATTRIBUTION.md` |",
        "| [prd-generator](https://github.com/jamesrochabrun/skills) | James Rochabrun | MIT "
        "| `skills/productivity/agile-prd-creator` | inline in [README.md](./README.md) |",
        "| [claude-skill-management-consultant-B1](https://github.com/DogInfantry/claude-skill-management-consultant-B1) "
        "| DogInfantry | Apache-2.0 | `skills/productivity/management-consultant` | inline in [README.md](./README.md) |",
        "",
        "Nothing here changes the licence of the original work. If you are an author listed above and",
        "an attribution is wrong, open an issue and it will be corrected.",
        "",
    ]
    return "\n".join(out)


# ----------------------------------------------------------------------- core


def path_specs(source: dict) -> list:
    """Normalise a source's declared paths."""
    specs = source.get("paths")
    if not specs:
        _fail(f"[{source.get('id')}] manifest source declares no `paths`")
    out = []
    for spec in specs:
        kind = spec.get("kind", SKILL_COLLECTION)
        if kind not in (SKILL_COLLECTION, SUPPORT):
            _fail(f"[{source['id']}] unknown path kind `{kind}`")
        out.append(
            {
                "from": (spec.get("from") or "").strip("/"),
                "to": (spec.get("to") or "").strip("/"),
                "kind": kind,
                "include": spec.get("include", ["*"]),
                "exclude": spec.get("exclude", []),
                "exclude_reasons": spec.get("exclude_reasons", {}),
            }
        )
    return out


def process_source(source: dict, checkout: Path, sha: str, apply: bool) -> dict:
    dest_root = REPO_ROOT / source["dest"]
    plan = path_specs(source)
    added, removed, changed = [], [], []

    for spec in plan:
        upstream = checkout / spec["from"] if spec["from"] else checkout
        if not upstream.is_dir():
            _fail(f"[{source['id']}] upstream path not found: {spec['from'] or '<root>'}")
        local = dest_root / spec["to"] if spec["to"] else dest_root

        if spec["kind"] == SKILL_COLLECTION:
            selected = _selected(_child_dirs(upstream), spec["include"], spec["exclude"])
            existing = _child_dirs(local)
            spec["selected"] = selected
            added += [f"{spec['to']}/{n}" for n in selected if n not in existing]
            removed += [f"{spec['to']}/{n}" for n in existing if n not in selected]
            changed += [
                f"{spec['to']}/{n}"
                for n in selected
                if n in existing and tree_digest(local / n) != tree_digest(upstream / n)
            ]
            if apply:
                for name in existing:
                    if name not in selected:
                        shutil.rmtree(local / name)
                for name in selected:
                    target = local / name
                    if target.exists():
                        shutil.rmtree(target)
                    shutil.copytree(
                        upstream / name, target, ignore=shutil.ignore_patterns(".git")
                    )
                    upstream_path = (
                        posixpath.join(spec["from"], name) if spec["from"] else name
                    )
                    _write(
                        target / "PROVENANCE.md",
                        provenance_text(source, upstream_path, target, sha, "skill"),
                    )
        else:
            spec["selected"] = []
            if tree_digest(local) != tree_digest(upstream):
                changed.append(f"{spec['to'] or '.'}/ (support tree)")
            if apply:
                if local.exists():
                    shutil.rmtree(local)
                shutil.copytree(upstream, local, ignore=shutil.ignore_patterns(".git"))
                _write(
                    local / "PROVENANCE.md",
                    provenance_text(
                        source, spec["from"] or ".", local, sha, "support files, linked to by skills"
                    ),
                )

    all_selected = [n for spec in plan for n in spec.get("selected", [])]
    missing_mandatory = [m for m in (source.get("mandatory") or []) if m not in all_selected]

    if apply:
        lic = source.get("license_path")
        if lic and (checkout / lic).exists():
            _write(
                dest_root / "LICENSE.upstream",
                f"Vendored from {source['repo']} at commit {sha}.\n"
                f"Original licence text follows, unmodified.\n"
                f"{'-' * 76}\n\n" + (checkout / lic).read_text(encoding="utf-8"),
            )
        elif lic:
            _fail(f"[{source['id']}] declared license_path `{lic}` not found upstream")
        _write(dest_root / "ATTRIBUTION.md", attribution_text(source, sha, plan))

    return {
        "id": source["id"],
        "dest": source["dest"],
        "pinned_commit": source.get("pinned_commit"),
        "upstream_commit": sha,
        "commit_moved": source.get("pinned_commit") != sha,
        "selected_count": len(all_selected),
        "added": sorted(added),
        "removed": sorted(removed),
        "changed": sorted(changed),
        "missing_mandatory": missing_mandatory,
    }


def validate_manifest(manifest: dict) -> list:
    """Offline invariants. Fast enough to gate every pull request.

    Answers the question a reviewer actually has: does the tree still match what
    the manifest claims about it? No network, so an upstream commit moving does
    not turn unrelated pull requests red.
    """
    problems = []
    seen_ids, seen_dests = set(), set()

    for src in manifest.get("sources", []):
        sid = src.get("id", "<missing id>")
        for field in ("id", "name", "repo", "author", "license", "dest", "pinned_commit", "paths"):
            if not src.get(field):
                problems.append(f"[{sid}] source is missing required field `{field}`")
        if sid in seen_ids:
            problems.append(f"[{sid}] duplicate manifest source id")
        seen_ids.add(sid)

        dest = (src.get("dest") or "").strip("/")
        if dest in seen_dests:
            problems.append(f"[{sid}] two sources vendor into the same dest `{dest}`")
        seen_dests.add(dest)

        sha = src.get("pinned_commit", "")
        if sha and not SHA_RE.match(sha):
            problems.append(f"[{sid}] pinned_commit must be a full 40-char sha, got `{sha}`")

        dest_root = REPO_ROOT / dest
        if not dest_root.is_dir():
            problems.append(f"[{sid}] dest `{dest}` does not exist; run --sync")
            continue
        for required in ("ATTRIBUTION.md", "LICENSE.upstream"):
            if not (dest_root / required).exists():
                problems.append(f"[{sid}] `{dest}/{required}` is missing; run --sync")

        if not src.get("paths"):
            continue
        found = []
        for spec in path_specs(src):
            local = dest_root / spec["to"] if spec["to"] else dest_root
            for name in spec.get("exclude") or []:
                if name not in (spec.get("exclude_reasons") or {}):
                    problems.append(
                        f"[{sid}] `{spec['from']}/{name}` is excluded with no reason recorded"
                    )
            for name in spec.get("exclude_reasons") or {}:
                if name not in (spec.get("exclude") or []):
                    problems.append(
                        f"[{sid}] exclude_reasons documents `{name}` but exclude omits it"
                    )
            if not local.is_dir():
                problems.append(f"[{sid}] mapped path `{dest}/{spec['to']}` missing; run --sync")
                continue

            if spec["kind"] == SKILL_COLLECTION:
                for name in _child_dirs(local):
                    child = local / name
                    found.append(name)
                    if _has_skill(child) and not (child / "PROVENANCE.md").exists():
                        problems.append(
                            f"[{sid}] `{dest}/{spec['to']}/{name}` has no PROVENANCE.md; run --sync"
                        )
                    if any(fnmatch.fnmatch(name, p) for p in spec.get("exclude", [])):
                        problems.append(
                            f"[{sid}] `{dest}/{spec['to']}/{name}` is present but excluded"
                        )
            elif not (local / "PROVENANCE.md").exists():
                problems.append(
                    f"[{sid}] support tree `{dest}/{spec['to']}` has no PROVENANCE.md; run --sync"
                )

        for name in src.get("mandatory") or []:
            if name not in found:
                problems.append(f"[{sid}] mandatory skill `{name}` is not vendored into `{dest}`")

    if not NOTICES_PATH.exists():
        problems.append("THIRD_PARTY_NOTICES.md is missing; run --sync")
    else:
        notices = NOTICES_PATH.read_text(encoding="utf-8")
        for src in manifest.get("sources", []):
            if src.get("pinned_commit") and src["pinned_commit"] not in notices:
                problems.append(
                    f"[{src.get('id')}] THIRD_PARTY_NOTICES.md does not cite the pinned commit; run --sync"
                )
    return problems


def main(argv: list) -> int:
    ap = argparse.ArgumentParser(description="Import and refresh vendored upstream skills.")
    mode = ap.add_mutually_exclusive_group(required=True)
    mode.add_argument(
        "--validate-manifest",
        action="store_true",
        help="offline check that the tree still matches the manifest",
    )
    mode.add_argument("--check", action="store_true", help="report upstream drift, write nothing")
    mode.add_argument("--sync", action="store_true", help="apply upstream into the working tree")
    ap.add_argument("--source", action="append", help="limit to a manifest source id (repeatable)")
    ap.add_argument("--output", choices=("text", "json"), default="text")
    args = ap.parse_args(argv)

    manifest = load_manifest()

    if args.validate_manifest:
        problems = validate_manifest(manifest)
        if args.output == "json":
            print(json.dumps({"ok": not problems, "problems": problems}, indent=2))
        else:
            for problem in problems:
                print(f"error: {problem}")
            print()
            print(
                f"{len(manifest.get('sources', []))} vendored source(s) checked, "
                f"{len(problems)} problem(s)"
            )
        return 1 if problems else 0

    if not shutil.which("git"):
        _fail("git is required and was not found on PATH")

    sources = manifest.get("sources", [])
    if args.source:
        sources = [s for s in sources if s["id"] in args.source]
        if not sources:
            _fail(f"no manifest source matched {args.source}")
    if not sources:
        _fail("manifest declares no sources")

    results = []
    with tempfile.TemporaryDirectory(prefix="vendor-sync-") as tmp:
        for source in sources:
            checkout, sha = fetch_upstream(source, Path(tmp))
            results.append(process_source(source, checkout, sha, apply=args.sync))
            if args.sync:
                source["pinned_commit"] = sha
                source["pinned_at"] = _dt.date.today().isoformat()

    if args.sync:
        MANIFEST_PATH.write_text(
            json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
        )
        _write(NOTICES_PATH, notices_text(manifest))

    blocked = [r for r in results if r["missing_mandatory"]]
    drift = [r for r in results if r["added"] or r["removed"] or r["changed"] or r["commit_moved"]]

    if args.output == "json":
        print(
            json.dumps(
                {
                    "mode": "sync" if args.sync else "check",
                    "drift": bool(drift),
                    "blocked": bool(blocked),
                    "sources": results,
                },
                indent=2,
            )
        )
    else:
        for r in results:
            print(f"[{r['id']}] -> {r['dest']}")
            print(
                f"  upstream commit : {r['upstream_commit'][:12]}"
                + ("  (moved)" if r["commit_moved"] else "  (unchanged)")
            )
            print(f"  tracked skills  : {r['selected_count']}")
            for key in ("added", "removed", "changed"):
                if r[key]:
                    print(f"  {key:<15} : {', '.join(r[key])}")
            if r["missing_mandatory"]:
                print(f"  MANDATORY MISSING: {', '.join(r['missing_mandatory'])}")
        print()
        if args.sync:
            print("drift applied" if drift else "nothing to apply")
        else:
            print("drift detected" if drift else "no drift detected")

    if blocked:
        print(
            "error: a skill listed as mandatory is absent from the selection; "
            "fix include/exclude in skills/vendor.manifest.json",
            file=sys.stderr,
        )
        return 1
    if args.check and drift:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
